# Generated by Django 2.0.2 on 2018-02-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unit', models.CharField(choices=[('mg', 'miligrama'), ('g', 'grama'), ('kg', 'kilograma'), ('ml', 'mililitro'), ('l', 'litro'), ('us_cup', 'xícara'), ('us_tbsp', 'colher de sopa'), ('us_tsp', 'colher de chá')], default='mg', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Portion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='portion',
            name='products',
            field=models.ManyToManyField(related_name='portions', through='recipes.Recipe', to='recipes.Product'),
        ),
        migrations.AddField(
            model_name='portion',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.SubProduct'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subproducts',
            field=models.ManyToManyField(related_name='ingredients', through='recipes.Portion', to='recipes.SubProduct'),
        ),
        migrations.AlterUniqueTogether(
            name='portion',
            unique_together={('ingredient', 'subproduct')},
        ),
    ]
