# Generated by Django 2.0.2 on 2018-02-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20180227_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='long_name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='short_name',
            new_name='value',
        ),
    ]
