# Generated by Django 2.0.2 on 2018-03-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180227_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SubProductPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portions', to='recipes.Product')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.SubProduct')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='portion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='portion',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='products',
        ),
        migrations.RemoveField(
            model_name='portion',
            name='subproduct',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='portion',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='subproducts',
        ),
        migrations.DeleteModel(
            name='Portion',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='ingredientportion',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientportion',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portions', to='recipes.SubProduct'),
        ),
    ]
