# Generated by Django 2.0.2 on 2018-03-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180303_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproductportion',
            name='unit',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, related_name='subproduct_portions', to='recipes.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='recipes.Unit'),
        ),
    ]
